name: Go

on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install --prefix=./web/admin/assets/web --force
      - run: npm run build --prefix=./web/admin/assets/web --force

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Build-Macos
        run: GOOS=darwin GOARCH=amd64 go build -o ./dist/gofound_macos_amd64

      - name: Build-Macos-Arm64
        run: GOOS=darwin GOARCH=arm64 go build -o ./dist/gofound_macos_apple_silicon

      - name: Build-Windows-x64
        run: GOOS=windows GOARCH=amd64 go build -o ./dist/gofound_windows_amd64.exe

      - name: Build-Windows-AMR64
        run: GOOS=windows GOARCH=arm64 go build -o ./dist/gofound_windows_arm64.exe

      - name: Build-Linux-x64
        run: GOOS=linux GOARCH=amd64 go build -o ./dist/gofound_linux_amd64

      - name: Build-Linux-AMR64
        run: GOOS=linux GOARCH=arm64 go build -o ./dist/gofound_linux_arm64

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./dist/* 
